sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"

env:
  global:
    - COMPOSER_FLAGS=""
    - EXTRA_PHPUNIT_PARAMS=""

before_install:
  - composer self-update

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit $EXTRA_PHPUNIT_PARAMS
