services:
    simple_bus.jms_serializer.object_serializer:
        class: SimpleBus\JMSSerializerBridge\JMSSerializerObjectSerializer
        public: false
        arguments:
            - '@jms_serializer'
            - 'json'
