services:
    simple_bus.asynchronous.envelope_factory:
        alias: simple_bus.asynchronous.default_envelope_factory
        public: true

    simple_bus.asynchronous.default_envelope_factory:
        class: SimpleBus\Serialization\Envelope\DefaultEnvelopeFactory
        public: false

    simple_bus.asynchronous.message_serializer:
        alias: simple_bus.asynchronous.standard_message_in_envelop_serializer
        public: true

    simple_bus.asynchronous.standard_message_in_envelop_serializer:
        class: SimpleBus\Serialization\Envelope\Serializer\StandardMessageInEnvelopeSerializer
        public: false
        arguments:
            - '@simple_bus.asynchronous.envelope_factory'
            # configured inside the bundle configuration
            - '@simple_bus.asynchronous.object_serializer'
