sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"

    # Test Symfony versions
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.* REMOVE_PROXY_BRIDGE="yes" EXTRA_PHPUNIT_PARAMS="--group SymfonyBridgeProxyManagerDependency"
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
    - php: 7.4
      env: SYMFONY_VERSION=4.4.* REMOVE_PROXY_BRIDGE="yes" EXTRA_PHPUNIT_PARAMS="--group SymfonyBridgeProxyManagerDependency"

env:
  global:
    - COMPOSER_FLAGS=""
    - EXTRA_PHPUNIT_PARAMS=""
    - REMOVE_PROXY_BRIDGE="no"
    - SYMFONY_VERSION=""

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/http-kernel:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/yaml:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/monolog-bridge:$SYMFONY_VERSION symfony/framework-bundle:$SYMFONY_VERSION symfony/proxy-manager-bridge:$SYMFONY_VERSION; fi

install:
  - composer update --prefer-dist $COMPOSER_FLAGS
  - if [ "$REMOVE_PROXY_BRIDGE" == "yes" ]; then composer remove symfony/proxy-manager-bridge; fi

script:
  - ./vendor/bin/phpunit $EXTRA_PHPUNIT_PARAMS
