<?php

/**
 * Copyright (c) 2013-2017 Matthias Noback.
 */

namespace SimpleBus\DoctrineORMBridge\Tests\PHPUnitTestServiceContainer\PHPUnit;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use SimpleBus\DoctrineORMBridge\Tests\PHPUnitTestServiceContainer\ServiceProvider\DoctrineDbalServiceProvider;

trait TestCaseWithDoctrineDbalConnection
{
    use TestCaseWithServiceContainer;

    /**
     * Return a Schema object. The DoctrineDbalServiceProvider will execute the SQL statements generated by it to
     * prepare the database for your tests.
     */
    abstract protected function createSchema(): Schema;

    protected function getServiceProviders(): array
    {
        $schema = $this->createSchema();

        return [
            new DoctrineDbalServiceProvider($schema),
        ];
    }

    /**
     * Get the Doctrine DBAL connection.
     */
    protected function getConnection(): Connection
    {
        return $this->container['doctrine_dbal.connection'];
    }
}
