services:
    simple_bus.asynchronous.event_publisher:
        public: true
        alias: simple_bus.rabbit_mq_bundle_bridge.event_publisher

    simple_bus.rabbit_mq_bundle_bridge.event_publisher:
        class: SimpleBus\RabbitMQBundleBridge\RabbitMQPublisher
        public: true
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - '@simple_bus.asynchronous.message_serializer'
            # defined in this bundle's configuration
            - '@simple_bus.rabbit_mq_bundle_bridge.event_producer'
            - '@simple_bus.rabbit_mq_bundle_bridge.routing.events_routing_key_resolver'
            - '@simple_bus.rabbit_mq_bundle_bridge.delegating_additional_properties_resolver'

    simple_bus.rabbit_mq_bundle_bridge.events_consumer:
        class: SimpleBus\RabbitMQBundleBridge\RabbitMQMessageConsumer
        public: true
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - '@simple_bus.asynchronous.standard_serialized_event_envelope_consumer'
            - '@event_dispatcher'
