services:
    simple_bus.rabbit_mq_bundle_bridge.delegating_additional_properties_resolver:
        class: SimpleBus\Asynchronous\Properties\DelegatingAdditionalPropertiesResolver
        public: false
        arguments:
         - []
