name: composer normalize

on: [ push ]

env:
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    build-matrix:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   run: composer install --no-progress --ansi
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json)"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    root:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: composer install --no-progress --ansi
            - run: composer normalize --dry-run

    packages:
        needs: build-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: composer install --no-progress --ansi
              working-directory: packages/${{ matrix.package }}
            - run: composer normalize --dry-run
              working-directory: packages/${{ matrix.package }}
