name: Composer validation

on: [ push ]

env:
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build-matrix:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # Remove `ignore-platform-req` when these issues are fixed
            # https://github.com/php-amqplib/php-amqplib/issues/846
            # https://github.com/schmittjoh/JMSSerializerBundle/pull/819
            -   name: Install dependencies
                uses: ramsey/composer-install@1.2.0
                with:
                    composer-options: "--ignore-platform-req php"
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json)"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    root:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Install dependencies
                uses: ramsey/composer-install@1.2.0
            -   run: composer validate
            -   run: composer normalize --dry-run

    packages:
        needs: build-matrix
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Install dependencies
                uses: ramsey/composer-install@1.2.0
                with:
                    working-directory: packages/${{ matrix.package }}
            -   run: composer validate
                working-directory: packages/${{ matrix.package }}
            -   run: composer normalize --dry-run
                working-directory: packages/${{ matrix.package }}
